apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-public
  labels:
    app: nginx-public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-public
  template:
    metadata:
      labels:
        app: nginx-public
    spec:
      containers:
      - name: nginx-public
        image: image-registry.openshift-image-registry.svc:5000/tekton-pipelines/nginx@sha256:0c30d4e668358a64fec2e242c86a64a968abbc5f0e727460a6d6714848f07d0c
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: my-nginx-public-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-public
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081